services:
  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux
    restart: unless-stopped
    networks:
      - proxy
    depends_on:
      minifluxdb:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:DB_PASSWORD@minifluxdb/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - BASE_URL=https://subdomain.domain.com
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=YOUR_USERNAME
      - ADMIN_PASSWORD=YOUR_PASSWORD
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.miniflux.rule=Host(`subdomain.domain.com`)
      - traefik.http.routers.miniflux.entrypoints=https
      - traefik.http.routers.miniflux.tls=true
  minifluxdb:
    image: postgres:15
    container_name: miniflux-db
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=DB_PASSWORD
      - POSTGRES_DB=miniflux
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - miniflux
      interval: 10s
      start_period: 30s
volumes:
  miniflux-db: null
networks:
  proxy:
    external: true