services:
  postgres:
    container_name: linkwarden-db
    image: postgres:16-alpine
    env_file: .env
    restart: always
    networks:
      - proxy
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  linkwarden:
    container_name: linkwarden
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      - NEXT_PUBLIC_DISABLE_REGISTRATION=true # add this line only after creating your user
      - DISABLE_NEW_SSO_USERS=true # add this line only after creating your user
    restart: always
    image: ghcr.io/linkwarden/linkwarden:latest
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.linkwarden.rule=Host(`subdomain.domain.com`)
      - traefik.http.routers.linkwarden.entrypoints=https
      - traefik.http.routers.linkwarden.tls=true
      - traefik.http.services.linkwarden.loadbalancer.server.port=3000
networks:
  proxy:
    external: true