version: '3.8'
services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      GID: "${GID-1000}"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik crowdsecurity/http-cve"
    volumes:
      - ./config/acquis.yaml:/etc/crowdsec/acquis.yaml
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
      - traefik_traefik-logs:/var/log/traefik/:ro
    networks:
      - proxy
    restart: unless-stopped

  # UNCOMMENT THIS WHOLE SECTION BELOW AFTER YOU RUN CROWDSEC FIRST AND OBTAIN THE BOUNCER API KEY AND PASTE IT BELOW. REFER TO THE README.

  #bouncer-traefik:
    #image: docker.io/fbonalair/traefik-crowdsec-bouncer:latest
    #container_name: bouncer-traefik
    #environment:
      #CROWDSEC_BOUNCER_API_KEY: PASTE_YOUR_BOUNCER_API_KEY_HERE
      #CROWDSEC_AGENT_HOST: crowdsec:8080
    #networks:
      #- proxy # same network as traefik + crowdsec
    #depends_on:
      #- crowdsec
    #restart: unless-stopped

networks:
  proxy:
    external: true
volumes:
  crowdsec-db:
  crowdsec-config:
  traefik_traefik-logs: # this will be the name of the volume from trarfic logs
    external: true # remove if traefik is running on same stack
